"""Generate THIRD_PARTY_NOTICES.md from the runtime dependencies (Python and npm).

    uv run python scripts/licenses.py

Flags anything that isn't a well-known permissive license so it can be reviewed before a release.
"""

import json
import os
import re
import subprocess
from importlib import metadata

ROOT = os.path.join(os.path.dirname(__file__), "..")
# Weak copyleft: fine to depend on unmodified, listed separately for transparency
WEAK_COPYLEFT = re.compile(r"\b(MPL|Mozilla Public License|EPL|Eclipse Public License)", re.I)
PERMISSIVE = re.compile(
    r"\b(MIT|BSD|Apache|ISC|PSF|Python Software Foundation|0BSD|Unlicense|CC0|BlueOak|Zlib|MPL-2\.0|CC-BY-4\.0)",
    re.I,
)


def python_deps():
    out = subprocess.run(
        ["uv", "export", "--no-dev", "--no-hashes", "--no-emit-project", "--format", "requirements-txt"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    names = sorted({line.split("==")[0].strip() for line in out.splitlines() if "==" in line and not line.startswith("#")})
    rows = []
    for name in names:
        try:
            md = metadata.metadata(name)
        except metadata.PackageNotFoundError:
            continue
        lic = md.get("License-Expression") or ""
        if not lic or len(lic) > 60:
            classifiers = [c.split("::")[-1].strip() for c in md.get_all("Classifier") or [] if c.startswith("License ::")]
            lic = ", ".join(classifiers) or (md.get("License") or "").splitlines()[0][:60]
        rows.append((name, md.get("Version"), lic or "UNKNOWN", md.get("Home-page") or ""))
    return rows


def npm_deps():
    lock = json.load(open(os.path.join(ROOT, "frontend", "package-lock.json")))
    rows = []
    for path, info in lock["packages"].items():
        if not path or info.get("dev") or info.get("devOptional"):
            continue
        name = path.split("node_modules/")[-1]
        pkg_json = os.path.join(ROOT, "frontend", path, "package.json")
        lic = info.get("license")
        if not lic and os.path.exists(pkg_json):
            lic = json.load(open(pkg_json)).get("license")
        if not lic:  # some packages only ship a license file
            for fname in ("license", "LICENSE", "LICENSE.md", "license.md"):
                fpath = os.path.join(ROOT, "frontend", path, fname)
                if os.path.exists(fpath):
                    first = open(fpath).read(200)
                    lic = "MIT" if "MIT" in first else first.splitlines()[0].strip()
                    break
        rows.append((name, info.get("version"), lic or "UNKNOWN", ""))
    return sorted(set(rows))


def main():
    py, js = python_deps(), npm_deps()
    weak = [(n, v, lic) for n, v, lic, _ in py + js if WEAK_COPYLEFT.search(str(lic))]
    flagged = [(n, v, lic) for n, v, lic, _ in py + js
               if not PERMISSIVE.search(str(lic)) and not WEAK_COPYLEFT.search(str(lic))]
    lines = [
        "# Third-party notices",
        "",
        "Quorum is released under the [MIT License](LICENSE). It depends on the open-source packages below,",
        "each under its own license. This file is generated by `scripts/licenses.py`.",
        "",
        "## Services and assets that are not bundled",
        "",
        "- **Ollama** (MIT) is installed separately and runs the models.",
        "- **Models** are downloaded by you through Ollama or used through your own cloud API keys; each model has its",
        "  own license or terms of use.",
        "- **Firecrawl** (AGPL-3.0) is optional. `scripts/firecrawl.sh` clones it into `vendor/` on your machine and runs",
        "  its published Docker images; Quorum talks to it over HTTP and does not include or modify its code.",
        "- **Emoji** are drawn by your operating system's emoji font; no emoji artwork is included in this repository's code.",
        "- **Fonts** are your system fonts; none are bundled.",
        "",
        "## Weak-copyleft dependencies",
        "",
        "These are used unmodified as ordinary dependencies (installed by pip / npm, not copied into this repository),",
        "which their licenses allow. Their source is available from their projects.",
        "",
        *[f"- **{n}** {v}: {lic}" for n, v, lic in weak],
        "",
        f"## Python packages ({len(py)})",
        "",
        "| Package | Version | License |",
        "|---|---|---|",
        *[f"| {n} | {v} | {lic} |" for n, v, lic, _ in py],
        "",
        f"## JavaScript packages ({len(js)})",
        "",
        "| Package | Version | License |",
        "|---|---|---|",
        *[f"| {n} | {v} | {lic} |" for n, v, lic, _ in js],
        "",
    ]
    with open(os.path.join(ROOT, "THIRD_PARTY_NOTICES.md"), "w") as fh:
        fh.write("\n".join(lines))
    print(f"{len(py)} Python + {len(js)} npm packages → THIRD_PARTY_NOTICES.md")
    if flagged:
        print("Review these licenses:")
        for n, v, lic in flagged:
            print(f"  {n} {v}: {lic}")


if __name__ == "__main__":
    main()
